//   Copyright (c) 2024 KANEDA Akihiro <taoist.aki@gmail.com>
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using FluentAssertions;
using RedPen.Net.Core.Config;
using RedPen.Net.Core.Errors;
using RedPen.Net.Core.Model;
using RedPen.Net.Core.Tokenizer;
using RedPen.Net.Core.Validators.SentenceValidator;
using Xunit;
using Xunit.Abstractions;

namespace RedPen.Net.Core.Tests.Validators.SentenceValidator
{
    public class OkuriganaValidatorTests
    {
        private ITestOutputHelper output;

        public OkuriganaValidatorTests(ITestOutputHelper output)
        {
            this.output = output;
        }

        [Theory]
        [InlineData("001", "このタスクに長い年月を費してきた。", 1, "費し")]
        [InlineData("002", "このタスクに長い年月を費やしてきた。", 0, "")]
        [InlineData("003", "彼に合せた。", 1, "合せ")]
        [InlineData("004", "それとは競合している。", 0, "")]
        [InlineData("005", "そこを押えない。", 1, "押え")]
        [InlineData("006", "そこを押えて、", 1, "押え")]
        [InlineData("007", "そこを押える。", 1, "押える")]
        [InlineData("008", "そこを押える時、", 1, "押える")]
        [InlineData("009", "そこを押えれば、", 1, "押えれ")]
        [InlineData("010", "そこを押えよ！", 1, "押えよ")]
        [InlineData("011", "そこを押さえない。", 0, "")]
        [InlineData("012", "そこを押さえて、", 0, "")]
        [InlineData("013", "そこを押さえる。", 0, "")]
        [InlineData("014", "そこを押さえる時、", 0, "")]
        [InlineData("015", "そこを押さえれば、", 0, "")]
        [InlineData("016", "そこを押さえよ!", 0, "")]
        [InlineData("017", "花押を押す", 0, "")]
        [InlineData("018", "荷物を押収する", 0, "")]
        [InlineData("019", "あなたに、困難は起らない。", 1, "起ら")]
        [InlineData("020", "あなたに、困難が起る。", 1, "起る")]
        [InlineData("021", "あなたに困難が起る時、私は助けるだろう。", 1, "起る")]
        [InlineData("022", "あなたに困難が起れば、私は助けるだろう。", 1, "起れ")]
        [InlineData("023", "あなたに困難が起ろう。", 1, "起ろ")]
        [InlineData("024", "あなたは、起ない", 1, "起")]
        [InlineData("025", "わたしは、起よう！", 1, "起")]
        [InlineData("026", "あなたに、困難は起こらない。", 0, "")]
        [InlineData("027", "あなたに困難が起こって、私が助けた。", 0, "")]
        [InlineData("028", "あなたに、困難が起こる。", 0, "")]
        [InlineData("029", "あなたに困難が起こる時、私は助けるだろう。", 0, "")]
        [InlineData("030", "あなたに、困難が起ころう。", 0, "")]
        [InlineData("031", "あなたは、起きない。", 0, "")]
        [InlineData("032", "わたしは、起きて、顔を洗った。", 0, "")]
        [InlineData("033", "わたしは、起きる。", 0, "")]
        [InlineData("034", "わたしは、起きる時、あくびをした。", 0, "")]
        [InlineData("035", "わたしは、起きれば、出かけるだろう。", 0, "")]
        [InlineData("036", "わたしは、起きよう！", 0, "")]
        [InlineData("037", "この話には起承転結がない。", 0, "")]
        [InlineData("038", "わたしは、再帰するだろう。", 0, "")]
        [InlineData("039", "わたしは、喚起するだろう。", 0, "")]
        [InlineData("040", "わたしは、躍起になるだろう。", 0, "")]
        [InlineData("041", "あなたの成長は、著くない。", 1, "著く")]
        [InlineData("042", "あなたの成長が著くて、みんな喜んだ。", 1, "著く")]
        [InlineData("043", "あなたの成長は、著かろう。", 1, "著かろ")]
        [InlineData("044", "あなたの成長は、著かった。", 1, "著かっ")]
        [InlineData("045", "あなたの成長は、著い。", 1, "著い")]
        [InlineData("046", "あなたの成長が著い時、みんな喜ぶ。", 1, "著い")]
        [InlineData("047", "あなたの成長が著ければ、みんな喜ぶ。", 1, "著けれ")]
        [InlineData("048", "あなたの成長は、著しくない。", 0, "")]
        [InlineData("049", "あなたの成長が著しくて、みんな喜んだ。", 0, "")]
        [InlineData("050", "あなたの成長が、著しかろう。", 0, "")]
        [InlineData("051", "あなたの成長が、著しい。", 0, "")]
        [InlineData("052", "あなたの成長が著しい時、みんな喜んだ。", 0, "")]
        [InlineData("053", "あなたの成長が著しければ、みんな喜ぶだろう。", 0, "")]
        [InlineData("054", "徴候が顕著に現れる。", 0, "")]
        [InlineData("055", "あなたの成長が、著しかった。", 0, "")]
        [InlineData("056", "わたしは、冬期の単独登頂を試ない。", 1, "試")]
        [InlineData("057", "わたしは、冬期の単独登頂を試て、成功した。", 1, "試")]
        [InlineData("058", "わたしは、冬期の単独登頂を試る。", 1, "試")]
        [InlineData("059", "わたしが、冬期の単独登頂を試る時、応援されるだろう。", 1, "試")]
        [InlineData("060", "わたしが、冬期の単独登頂を試れば、応援されるだろう。", 1, "試")]
        [InlineData("061", "わたしは、冬期の単独登頂を試よう！", 1, "試")]
        [InlineData("062", "わたしは、冬期の単独登頂を試みない。", 0, "")]
        [InlineData("063", "わたしは、冬期の単独登頂を試みて、成功した。", 0, "")]
        [InlineData("064", "わたしが、冬期の単独登頂を試みる時、応援されるだろう。", 0, "")]
        [InlineData("065", "わたしが、冬期の単独登頂を試みれば、応援されるだろう。", 0, "")]
        [InlineData("066", "わたしは、冬期の単独登頂を試みよう！", 0, "")]
        [InlineData("067", "開発プロセスに問題ないと判断し、入試する。", 0, "")]
        [InlineData("068", "試験を休んだため追試になる。", 0, "")]
        [InlineData("069", "入試にむけて試験勉強をする。", 0, "")]
        [InlineData("070", "わたしはギャグがうけなくても、恥しくない。", 1, "恥しく")]
        [InlineData("071", "わたしはギャグがうけず恥しくて、苦笑いをした。", 1, "恥しく")]
        [InlineData("072", "あなたはギャグがうけず、恥しかろう。", 1, "恥しかろ")]
        [InlineData("073", "わたしはギャグがうけず、恥しかった。", 1, "恥しかっ")]
        [InlineData("074", "わたしはギャグがうけず、恥しい。", 1, "恥しい")]
        [InlineData("075", "わたしはギャグがうけず、恥しい時、苦笑いをする。", 1, "恥しい")]
        [InlineData("076", "あなたはギャグがうけず、恥しければ、苦笑いをする。", 1, "恥しけれ")]
        [InlineData("077", "わたしはギャグがうけなくても、恥ずかしくない。", 0, "")]
        [InlineData("078", "わたしはギャグがうけず恥ずかしくて、苦笑いをした。", 0, "")]
        [InlineData("079", "あなたはギャグがうけず恥ずかしかろう。", 0, "")]
        [InlineData("080", "わたしはギャグがうけず恥ずかしい。", 0, "")]
        [InlineData("081", "わたしはギャグがうけず恥ずかしい時、苦笑いをする。", 0, "")]
        [InlineData("082", "わたしはギャグがうけず恥ずかしければ、苦笑いをする。", 0, "")]
        [InlineData("083", "わたしは羞恥心をもっている。", 0, "")]
        [InlineData("084", "あなたは無恥な人です。", 0, "")]
        [InlineData("085", "わたしにはアイディアが生れない。", 1, "生れ")]
        [InlineData("086", "わたしにアイディアが生れて、行動した。", 1, "生れ")]
        [InlineData("087", "わたしに良いアイディアが生れる。", 1, "生れる")]
        [InlineData("088", "わたしに良いアイディアが生れる時、行動するだろう。", 1, "生れる")]
        [InlineData("089", "わたしに良いアイディアが生れれば、行動するだろう。", 1, "生れれ")]
        [InlineData("090", "わたしに良いアイディアが生れよ！", 1, "生れよ")]
        [InlineData("091", "わたしにはアイデアが生まれない。", 0, "")]
        [InlineData("092", "わたしにアイデアが生まれて、行動した。", 0, "")]
        [InlineData("093", "わたしにアイデアが生まれる。", 0, "")]
        [InlineData("094", "わたしにアイデアが生まれる時、行動するだろう。", 0, "")]
        [InlineData("095", "わたしにアイデアが生まれれば、行動するだろう。", 0, "")]
        [InlineData("096", "わたしにアイデアが生まれよ！", 0, "")]
        [InlineData("097", "わたしの一生の思い出。", 0, "")]
        [InlineData("098", "わたしは更生するだろう。", 0, "")]
        [InlineData("099", "あなたの業務を妨ない。", 1, "妨")]
        [InlineData("100", "あなたの業務を妨て、怒られた。", 1, "妨")]
        [InlineData("101", "あなたの業務を妨る。", 1, "妨")]
        [InlineData("102", "あなたの業務を妨る時、怒られるだろう。", 1, "妨")]
        [InlineData("103", "あなたの業務を妨れば、怒られるだろう。", 1, "妨")]
        [InlineData("104", "あなたの業務を妨よ！", 1, "妨")]
        [InlineData("105", "あなたの業務を妨げない。", 0, "")]
        [InlineData("106", "あなたの業務を妨げて、怒られた。", 0, "")]
        [InlineData("107", "あなたの業務を妨げる。", 0, "")]
        [InlineData("108", "あなたの業務を妨げる時、怒られるだろう。", 0, "")]
        [InlineData("109", "あなたの業務を妨げれば、怒られるだろう。", 0, "")]
        [InlineData("110", "あなたの業務を妨げよ！", 0, "")]
        [InlineData("111", "あなたの業務を妨害する。", 0, "")]
        [InlineData("112", "あなたは進路妨害をした。", 0, "")]
        [InlineData("113", "あなたはプロジェクトを進ない。", 1, "進")]
        [InlineData("114", "あなたはプロジェクトを進ていくだろ。", 1, "進")]
        [InlineData("115", "あなたはプロジェクトを進る。", 1, "進")]
        [InlineData("116", "あなたがプロジェクトを進る時、わたしはサポートする。", 1, "進")]
        [InlineData("117", "あなたがプロジェクトを進れば、わたしはサポートする。", 1, "進")]
        [InlineData("118", "あなたがプロジェクトを進よ！", 1, "進")]
        [InlineData("119", "あなたはプロジェクトを進めない。", 0, "")]
        [InlineData("120", "あなたはプロジェクトを進めていくだろう。", 0, "")]
        [InlineData("121", "あなたはプロジェクトを進める。", 0, "")]
        [InlineData("122", "あなたはプロジェクトを進める時、わたしはサポートする。", 0, "")]
        [InlineData("123", "あなたはプロジェクトを進めれば、わたしはサポートする。", 0, "")]
        [InlineData("124", "あなたはプロジェクトを進めよ！", 0, "")]
        [InlineData("125", "あなたは行進する。", 0, "")]
        [InlineData("126", "あなたは躍進した。", 0, "")]
        [InlineData("127", "あなたの性格は猪突猛進タイプだ。", 0, "")]
        [InlineData("128", "あなたにダイエットを勧ない。", 1, "勧")]
        [InlineData("129", "あなたにダイエットを勧て、わたしも一緒にやってみよう。", 1, "勧")]
        [InlineData("130", "あなたにダイエットを勧る。", 1, "勧")]
        [InlineData("131", "あなたにダイエットを勧る時、わたしも一緒にやってみよう。", 1, "勧")]
        [InlineData("132", "あなたにダイエットを勧れば、わたしも一緒にやってみる。", 1, "勧")]
        [InlineData("133", "あなたにダイエットを勧よ！", 1, "勧")]
        [InlineData("134", "あなたにダイエットを勧めない。", 0, "")]
        [InlineData("135", "あなたにダイエットを勧めて、わたしも一緒にやってみよう。", 0, "")]
        [InlineData("136", "あなたにダイエットを勧める。", 0, "")]
        [InlineData("137", "あなたにダイエットを勧める時、わたしも一緒にやってみよう。", 0, "")]
        [InlineData("138", "あなたにダイエットを勧めれば、わたしも一緒にやってみよう。", 0, "")]
        [InlineData("139", "あなたにダイエットを勧めよ！", 0, "")]
        [InlineData("140", "わたしは勧善懲悪なドラマが好きです。", 0, "")]
        [InlineData("141", "あなたは将来のことを考ない。", 1, "考")]
        [InlineData("142", "あなたは将来のことを考て、勉強する。", 1, "考")]
        [InlineData("143", "あなたは将来のことを考る。", 1, "考")]
        [InlineData("144", "あなたは将来のことを考る時、勉強するだろう。", 1, "考")]
        [InlineData("145", "あなたは将来のことを考れば、勉強するだろう。", 1, "考")]
        [InlineData("146", "あなたは将来のことを考よ！", 1, "考")]
        [InlineData("147", "あなたは将来のことを考えない。", 0, "")]
        [InlineData("148", "あなたは将来のことを考えて、勉強するだろう。", 0, "")]
        [InlineData("149", "あなたは将来のことを考える。", 0, "")]
        [InlineData("150", "あなたは将来のことを考える時、勉強するだろう。", 0, "")]
        [InlineData("151", "あなたは将来のことを考えれば、勉強するだろう。", 0, "")]
        [InlineData("152", "あなたは将来のことを考えよ！", 0, "")]
        [InlineData("153", "あなたは将来のことを再考する。", 0, "")]
        [InlineData("154", "あなたは過去のことを参考にする。", 0, "")]
        [InlineData("155", "これは参考情報です。", 0, "")]
        [InlineData("156", "あなたはどのような思考回路を持っているのだろう？", 0, "")]
        [InlineData("157", "あなたは決めたことを行なわない。", 1, "行なわ")]
        [InlineData("158", "あなたは決めたことを行なう。", 1, "行なう")]
        [InlineData("159", "あなたは決めたことを行なう時、信頼されるだろう。", 1, "行なう")]
        [InlineData("160", "あなたは決めたことを行なえば、信頼されるだろう。", 1, "行なえ")]
        [InlineData("161", "あなたは決めたことを行わない。", 0, "")]
        [InlineData("162", "あなたは決めたことを行わない。", 0, "")]
        [InlineData("163", "あなたは決めたことを行う。", 0, "")]
        [InlineData("164", "あなたは決めたことを行う時、信頼されるだろう。", 0, "")]
        [InlineData("165", "あなたは決めたことを行えば、信頼されるだろう。", 0, "")]
        [InlineData("166", "あなたの周りで不正が横行する。", 0, "")]
        [InlineData("167", "あなたは蛇行運転が得意です。", 0, "")]
        [InlineData("168", "あなたは旅行に行く。", 0, "")]
        [InlineData("169", "あなたは感情を顔に表わさない。", 1, "表わさ")]
        [InlineData("170", "あなたは感情を顔に表わす。", 1, "表わす")]
        [InlineData("171", "あなたが感情を顔に表わす時、意図が伝わるだろう。", 1, "表わす")]
        [InlineData("172", "あなたが感情を顔に表わせば、意図が伝わるだろう。", 1, "表わせ")]
        [InlineData("173", "あなたは感情を顔に表さない。", 0, "")]
        [InlineData("174", "あなたは感情を顔に表す。", 0, "")]
        [InlineData("175", "あなたは感情を顔に表す時、意図が伝わるだろう。", 0, "")]
        [InlineData("176", "あなたは感情を顔に表せば、意図が伝わるだろう。", 0, "")]
        [InlineData("177", "あなたは意表を突くのが得意だ。", 0, "")]
        [InlineData("178", "あなたは秘密を公表する。", 0, "")]
        [InlineData("179", "あなたが、現われない。", 1, "現われ")]
        [InlineData("180", "あなたが、現われて、会話した。", 1, "現われ")]
        [InlineData("181", "あなたが、現われる。", 1, "現われる")]
        [InlineData("182", "あなたが、現われる時、会話するだろう。", 1, "現われる")]
        [InlineData("183", "あなたが、現われれば、会話するだろう。", 1, "現われれ")]
        [InlineData("184", "あなたが、現われよ！", 1, "現われよ")]
        [InlineData("185", "あなたが現れない。", 0, "")]
        [InlineData("186", "あなたが現れて、会話した。", 0, "")]
        [InlineData("187", "あなたが現れる。", 0, "")]
        [InlineData("188", "あなたが現れる時、会話するだろう。", 0, "")]
        [InlineData("189", "あなたが現れれば、会話するだろう。", 0, "")]
        [InlineData("190", "あなたが現れよ！", 0, "")]
        [InlineData("191", "あなたの夢が実現する。", 0, "")]
        [InlineData("192", "あなたが発言した。", 0, "")]
        [InlineData("193", "あなたは、断わらない。", 1, "断わら")]
        [InlineData("194", "あなたは、断わる。", 1, "断わる")]
        [InlineData("195", "あなたが断わる時、困るだろう。", 1, "断わる")]
        [InlineData("196", "あなたが断われば、困るだろう。", 1, "断われ")]
        [InlineData("197", "あなたに断わろう。", 1, "断わろ")]
        [InlineData("198", "あなたは断らない。", 0, "")]
        [InlineData("199", "あなたが断って、困った。", 0, "")]
        [InlineData("200", "あなたが断る。", 0, "")]
        [InlineData("201", "あなたが断る時、困るだろう。", 0, "")]
        [InlineData("202", "あなたに断ろう。", 0, "")]
        [InlineData("203", "あなたは横断歩道を渡る。", 0, "")]
        [InlineData("204", "あなたは決断する。", 0, "")]
        [InlineData("205", "あなたは判断した。", 0, "")]
        [InlineData("206", "私には聞えない。", 1, "聞え")]
        [InlineData("207", "私には聞えて、", 1, "聞え")]
        [InlineData("208", "私には聞える。", 1, "聞える")]
        [InlineData("209", "私には聞える時、", 1, "聞える")]
        [InlineData("210", "私には聞えれば、", 1, "聞えれ")]
        [InlineData("211", "私には聞えよ！", 1, "聞えよ")]
        [InlineData("212", "私には聞こえない。", 0, "")]
        [InlineData("213", "私には聞こえて、", 0, "")]
        [InlineData("214", "私には聞こえる。", 0, "")]
        [InlineData("215", "私には聞こえる時、", 0, "")]
        [InlineData("216", "私には聞こえれば、", 0, "")]
        [InlineData("217", "私には聞こえよ！", 0, "")]
        [InlineData("218", "新聞を読む", 0, "")]
        [InlineData("219", "百聞は一見にしかず", 0, "")]
        [InlineData("220", "宝くじが当らない。", 1, "当ら")]
        [InlineData("221", "宝くじが当る。", 1, "当る")]
        [InlineData("222", "宝くじが当る時、", 1, "当る")]
        [InlineData("223", "宝くじが当れば、", 1, "当れ")]
        [InlineData("224", "宝くじに当ろう。", 1, "当ろ")]
        [InlineData("225", "宝くじが当たらない。", 0, "")]
        [InlineData("226", "宝くじが当たって、", 0, "")]
        [InlineData("227", "宝くじが当たる。", 0, "")]
        [InlineData("228", "宝くじが当たる時、", 0, "")]
        [InlineData("229", "宝くじが当たれば、", 0, "")]
        [InlineData("230", "宝くじに当たろう。", 0, "")]
        [InlineData("231", "私が該当する。", 0, "")]
        [InlineData("232", "見当違いしている", 0, "")]
        [InlineData("233", "私が担当した。", 0, "")]
        [InlineData("234", "荷物を落さない", 1, "落さ")]
        [InlineData("235", "荷物を落して", 1, "落し")]
        [InlineData("236", "荷物を落す。", 1, "落す")]
        [InlineData("237", "荷物を落す時、", 1, "落す")]
        [InlineData("238", "荷物を落せば、", 1, "落せ")]
        [InlineData("239", "荷物を落そう。", 1, "落そ")]
        [InlineData("240", "荷物を落とさない。", 0, "")]
        [InlineData("241", "荷物を落とさして、", 0, "")]
        [InlineData("242", "荷物を落として、", 0, "")]
        [InlineData("243", "荷物を落とす。", 0, "")]
        [InlineData("244", "荷物を落とす時、", 0, "")]
        [InlineData("245", "荷物を落とす。", 0, "")]
        [InlineData("246", "荷物を落とそう。", 0, "")]
        [InlineData("247", "感情が欠落している。", 0, "")]
        [InlineData("248", "先頭から脱落する", 0, "")]
        [InlineData("249", "勉強を終らさない。", 1, "終ら")]
        [InlineData("250", "勉強が終る。", 1, "終る")]
        [InlineData("251", "勉強が終る時、", 1, "終る")]
        [InlineData("252", "勉強が終れば、", 1, "終れ")]
        [InlineData("253", "勉強を終ろう。", 1, "終ろ")]
        [InlineData("254", "勉強を終わらさない。", 0, "")]
        [InlineData("255", "勉強が終わって、", 0, "")]
        [InlineData("256", "勉強が終わる。", 0, "")]
        [InlineData("257", "勉強が終わる時、", 0, "")]
        [InlineData("258", "勉強が終われば、", 0, "")]
        [InlineData("259", "勉強を終わろう。", 0, "")]
        [InlineData("260", "最終電車に乗る", 0, "")]
        [InlineData("261", "有終の美を飾る", 0, "")]
        [InlineData("262", "約束を果さない。", 1, "果さ")]
        [InlineData("263", "約束を果す。", 1, "果す")]
        [InlineData("264", "約束を果す時、", 1, "果す")]
        [InlineData("265", "約束を果せば、", 1, "果せ")]
        [InlineData("266", "約束を果そう。", 1, "果そ")]
        [InlineData("267", "約束を果たさない。", 0, "")]
        [InlineData("268", "約束を果たして、", 0, "")]
        [InlineData("269", "約束を果たす。", 0, "")]
        [InlineData("270", "約束を果たす時、", 0, "")]
        [InlineData("271", "約束を果たそう。", 0, "")]
        [InlineData("272", "因果関係を明らかにする", 0, "")]
        [InlineData("273", "結果を確認する", 0, "")]
        [InlineData("274", "成果をあげる", 0, "")]
        [InlineData("275", "性格は変らない。", 1, "変ら")]
        [InlineData("276", "性格は変らして、", 1, "変ら")]
        [InlineData("277", "性格は変る。", 1, "変る")]
        [InlineData("278", "性格が変るとき、", 1, "変る")]
        [InlineData("279", "性格を変らせれば、", 1, "変ら")]
        [InlineData("280", "性格が変わらない。", 0, "")]
        [InlineData("281", "性格を変わらして、", 0, "")]
        [InlineData("282", "性格を変わる。", 0, "")]
        [InlineData("283", "性格が変わるとき、", 0, "")]
        [InlineData("284", "性格が変わらせれば、", 0, "")]
        [InlineData("285", "異変に気付く。", 0, "")]
        [InlineData("286", "臨機応変に対応する", 0, "")]
        [InlineData("287", "病状が急変した", 0, "")]
        [InlineData("288", "テレビを買ない。", 1, "買")]
        [InlineData("289", "テレビを買て、", 1, "買")]
        [InlineData("290", "テレビを買る。", 1, "買")]
        [InlineData("291", "テレビを買る時、", 1, "買")]
        [InlineData("292", "テレビを買れば、", 1, "買")]
        [InlineData("293", "テレビを買よ！", 1, "買")]
        [InlineData("294", "テレビを買えない。", 0, "")]
        [InlineData("295", "テレビを買えて、", 0, "")]
        [InlineData("296", "テレビを買える。", 0, "")]
        [InlineData("297", "テレビを買える時、", 0, "")]
        [InlineData("298", "テレビを買えれば、", 0, "")]
        [InlineData("299", "テレビを買えよ！", 0, "")]
        [InlineData("300", "購買意欲が沸く", 0, "")]
        [InlineData("301", "テレビを売買する。", 0, "")]
        [InlineData("302", "仲買人から買う", 0, "")]
        [InlineData("303", "階段を上らない。", 1, "上ら")]
        [InlineData("304", "階段を上る。", 1, "上る")]
        [InlineData("305", "階段を上る時、", 1, "上る")]
        [InlineData("306", "階段を上れば、", 1, "上れ")]
        [InlineData("307", "階段を上がらない。", 0, "")]
        [InlineData("308", "階段を上がって、", 0, "")]
        [InlineData("309", "階段を上がる。", 0, "")]
        [InlineData("310", "階段を上がる時、", 0, "")]
        [InlineData("311", "階段を上がれば、", 0, "")]
        [InlineData("312", "屋上に移動する。", 0, "")]
        [InlineData("313", "陸上競技場に行く", 0, "")]
        [InlineData("314", "能力が向上する。", 0, "")]
        [InlineData("315", "お金を費さない。", 1, "費さ")]
        [InlineData("316", "お金を費して、", 1, "費し")]
        [InlineData("317", "お金を費す。", 1, "費す")]
        [InlineData("318", "お金を費す時、", 1, "費す")]
        [InlineData("319", "お金を費せば、", 1, "費せ")]
        [InlineData("320", "お金を費やさない。", 0, "")]
        [InlineData("321", "お金を費やして、", 0, "")]
        [InlineData("322", "お金を費やす。", 0, "")]
        [InlineData("323", "お金を費やすとき、", 0, "")]
        [InlineData("324", "お金を費やせば、", 0, "")]
        [InlineData("325", "会費を徴収する", 0, "")]
        [InlineData("326", "自費で参加する", 0, "")]
        [InlineData("327", "自分の身が危くない。", 1, "危く")]
        [InlineData("328", "自分の身が危く、", 1, "危く")]
        [InlineData("329", "自分の身が危い。", 1, "危い")] // TODO: この文は「危い」が正しいのか？
        [InlineData("330", "自分の身が危い時、", 1, "危い")] // TODO: この文は「危い」が正しいのか？
        [InlineData("331", "自分の身が危うくない。", 0, "")]
        [InlineData("332", "自分の身が危うく、", 0, "")]
        [InlineData("333", "自分の身が危うかった。", 0, "")]
        [InlineData("334", "自分の身が危うい。", 0, "")]
        [InlineData("335", "自分の身が危うい時、", 0, "")]
        [InlineData("336", "自分の身が危うければ、", 0, "")]
        [InlineData("337", "後ろに逸さない。", 1, "逸さ")]
        [InlineData("338", "後ろに逸して、", 1, "逸し")]
        [InlineData("339", "後ろに逸す。", 1, "逸す")]
        [InlineData("340", "後ろに逸す時、", 1, "逸す")]
        [InlineData("341", "後ろに逸らさない。", 0, "")]
        [InlineData("342", "後ろに逸らして、", 0, "")]
        [InlineData("343", "後ろに逸らす。", 0, "")]
        [InlineData("344", "後ろに逸らす時、", 0, "")]
        [InlineData("345", "体を反さない", 1, "反さ")]
        [InlineData("346", "体を反して、", 1, "反し")]
        [InlineData("347", "体を反す。", 1, "反す")]
        [InlineData("348", "体を反す時、", 1, "反す")]
        [InlineData("349", "体を反せば、", 1, "反せ")]
        [InlineData("350", "体を反そう。", 1, "反そ")]
        [InlineData("351", "体を反らさない。", 0, "")]
        [InlineData("352", "体を反らして、", 0, "")]
        [InlineData("353", "体を反らす。", 0, "")]
        [InlineData("354", "体を反らす時、", 0, "")]
        [InlineData("355", "体を反らせば、", 0, "")]
        [InlineData("356", "体を反らそう。", 0, "")]
        [InlineData("357", "ルールに違反する。", 0, "")]
        [InlineData("358", "謀反をおこす。", 0, "")]
        [InlineData("359", "家で過さない。", 1, "過さ")]
        [InlineData("360", "家で過して、", 1, "過し")]
        [InlineData("361", "家で過す。", 1, "過す")]
        [InlineData("362", "家で過す時、", 1, "過す")]
        [InlineData("363", "家で過せば、", 1, "過せ")]
        [InlineData("364", "家で過そう。", 1, "過そ")]
        [InlineData("365", "家で過ごさない。", 0, "")]
        [InlineData("366", "家で過ごして、", 0, "")]
        [InlineData("367", "家で過ごす。", 0, "")]
        [InlineData("368", "家で過ごす時、", 0, "")]
        [InlineData("369", "家で過ごせば、", 0, "")]
        [InlineData("370", "家で過ごそう。", 0, "")]
        [InlineData("371", "時間が経過する。", 0, "")]
        [InlineData("372", "通過点をとおる。", 0, "")]
        public void BasicTest(string nouse1, string text, int errorCount, string expected)

        {
            var validatorConfiguration = new OkuriganaConfiguration(ValidationLevel.ERROR);
            CultureInfo documentLang = CultureInfo.GetCultureInfo("ja-JP");

            // カスタムシンボルを使わない場合は空リストを渡す。デフォルトシンボルはnew時に自動的にSymbolTableにロードされる。
            SymbolTable symbolTable = new SymbolTable(documentLang, "", new List<Symbol>());

            // Validatorの生成。
            var validator = new OkuriganaValidator(
                documentLang,
                symbolTable,
                validatorConfiguration);

            // Tokenizeが走るので大仰でもDocumentを生成する。
            Document document = Document.Builder(RedPenTokenizerFactory.CreateTokenizer(documentLang))
                    .AddSection(1)
                    .AddParagraph()
                    .AddSentence(new Sentence(text, 1))
                    .Build(); // TokenizeをBuild時に実行する。

            var sentence = document.Sections[0].Paragraphs[0].Sentences[0];

            output.WriteLine("★全Token:");
            foreach (var token in sentence.Tokens)
            {
                output.WriteLine(token.ToString());
            }

            // Validation
            var errors = validator.Validate(sentence);

            errors.Should().HaveCount(errorCount);

            if (errors.Any())
            {
                var manager = new ErrorMessageManager();

                output.WriteLine("");
                output.WriteLine("★Errors:");
                foreach (var error in errors)
                {
                    output.WriteLine(error.ToString());
                    output.WriteLine(manager.GetErrorMessage(error, CultureInfo.GetCultureInfo("ja-JP")));
                }

                string.Join(",", errors.Select(e => e.MessageArgs[0].ToString())).Should().Be(expected);
            }
        }
    }
}
