//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPen.Net.Core {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedPen.Net.Core.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   iPhone
        ///mixi
        ///mRNA
        ///iTunes
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CapitalCaseExceptionList_en {
            get {
                return ResourceManager.GetString("CapitalCaseExceptionList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a
        ///the
        ///is
        ///are
        ///have
        ///has
        ///of
        ///to
        ///as
        ///　
        ///
        ///.
        ///“
        ///”
        ///&quot;
        ///&apos;
        ///、
        ///,
        ///，
        ///@
        ///#
        ///%
        ///=
        ///(
        ///)
        ///-
        ///_
        ////
        ///ー
        ///|
        ///0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///**
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubledWordSkiplist_en {
            get {
                return ResourceManager.GetString("DoubledWordSkiplist_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   の
        ///な
        ///が
        ///を
        ///に
        ///は
        ///　
        /// 
        ///た
        ///で
        ///し
        ///さ
        ///“
        ///”
        ///&quot;
        ///&apos;
        ///で
        ///、
        ///,
        ///，
        ///する
        ///いる
        ///ます
        ///ない
        ///れる
        ///と
        ///て
        ///@
        ///#
        ///%
        ///=
        ///や
        ///もの
        ///れ
        ///も
        ///（
        ///(
        ///）
        ///)
        ///-
        ///_
        ////
        ///／
        ///ー
        ///|
        ///0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///０
        ///１
        ///２
        ///３
        ///４
        ///５
        ///６
        ///７
        ///８
        ///９
        ///**
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubledWordSkiplist_ja {
            get {
                return ResourceManager.GetString("DoubledWordSkiplist_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   unless + not
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubleNegativeExpression_en {
            get {
                return ResourceManager.GetString("DoubleNegativeExpression_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ない + こと + も + ない
        ///ない + こと + * + ない
        ///ない + こと + ない
        ///ない + 事 + も + ない
        ///ない + 事 + * + ない
        ///ない + と + * + ない
        ///ない + と + * + かぎら + ない
        ///ない + と + いえ + ない
        ///ない + と + * + は + いえ + ない
        ///ない + わけ + で + は + ない
        ///ない + わけ + で + * + ない
        ///なく + は + ない
        ///なく + ない
        ///無く + ない
        ///無く + は + ない
        ///無い + こと + も + 無い
        ///無い + こと + * + 無い
        ///無い + 事 + も + 無い
        ///無い + 事 + 無い
        ///無い + 事 + * + 無い
        ///無い + と + * + 無い
        ///無い + と + * + かぎら + 無い
        ///無い + わけ + で + は + 無い
        ///無い + わけ + で + * + 無い
        ///なく + は + ない
        ///なく + ない
        ///無く + は + ない
        ///ず + に + は + い + られ + ない
        ///ず + に + い + られ + ない
        ///ず + に +  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubleNegativeExpression_ja {
            get {
                return ResourceManager.GetString("DoubleNegativeExpression_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   not
        ///unless
        ///never
        ///no
        ///none
        ///don&apos;t
        ///doesn&apos;t
        ///haven&apos;t
        ///hasn&apos;t
        ///hadn&apos;t
        ///impossible
        ///without
        ///little
        ///hardly
        ///seldom
        ///neither
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubleNegativeWord_en {
            get {
                return ResourceManager.GetString("DoubleNegativeWord_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubleNegativeWord_ja {
            get {
                return ResourceManager.GetString("DoubleNegativeWord_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hey!
        ///You know
        /// kick ass
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidExpression_en {
            get {
                return ResourceManager.GetString("InvalidExpression_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オワタ
        ///ってゆっか
        ///ってゆうか
        ///つーか、
        ///マジですか
        ///マジっす
        ///そんなばかな
        ///バカな
        ///馬鹿
        ///いっぺんに
        ///してない
        ///すごいね
        ///スゲーっ
        ///スゲーッ
        ///みたいな
        ///じゃない
        ///じゃなく
        ///ぶっちゃけ
        ///＼(^o^)／
        ///／＾o＾＼ﾌｯｼﾞｻｰﾝ
        ///アカンやつ
        ///だから、
        ///俺
        ///俺ら
        ///俺たち
        ///俺達
        ///だと思います
        ///思っています
        ///半端ない
        ///最高
        ///どういうふうに
        ///することができ
        ///することが可能
        ///考えられる
        ///非常に
        ///死ね
        ///死ぬ
        ///ゴミクズ
        ///アホか
        ///低能
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidExpression_ja {
            get {
                return ResourceManager.GetString("InvalidExpression_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   like
        ///likes
        ///liked
        ///hey
        ///can&apos;t
        ///won&apos;t
        ///kick
        ///fool
        ///foolish
        ///fucking
        ///fuck
        ///hell
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidWord_en {
            get {
                return ResourceManager.GetString("InvalidWord_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidWord_ja {
            get {
                return ResourceManager.GetString("InvalidWord_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロック
        ///コンテンツ
        ///コンテナ
        ///カタカナ
        ///リスナー
        ///ブラジル
        ///アニメ
        ///アニメーション
        ///アメリカンフットボール
        ///ワールドカップ
        ///サッカー
        ///フットボール
        ///キーボード
        ///モニター
        ///ディスプレイ
        ///ノート
        ///ノートパソコン
        ///エナジー
        ///エナジードリンク
        ///インデクス
        ///インデックス
        ///ロック
        ///フィリップフロップ
        ///スタンド
        ///コンパイラ
        ///コンパイル
        ///スペース
        ///スペルミス
        ///コマンドライン
        ///コマンドラインツール
        ///マニュアル
        ///フォーマット
        ///ヨーグルト
        ///フェルナンド
        ///インフィニティ
        ///パーティシーズン
        ///マシンガントーク
        ///ヒットシリーズ
        ///ノックアウト
        ///メークアップ
        ///パートナーシップ
        ///カウボーイ
        ///ミレニアム
        ///ロックスクリーン
        ///プロメテウス
        ///フェラーリ
        ///キャリアウーマン
        ///タジキスタン
        ///ワシコウスカ
        ///ブリーズライト
        ///データカード
        ///ビークリーム
        ///トッピング
        ///ストリーミング
        ///スポーツジム
        ///テンパリスト
        ///トライイベント
        ///サイクルモード
        ///ベネズエラ
        ///ニュータイプ
        ///パナボード
        ///プラセンタ
        ///ハイビジョン
        ///ダイバーシティ
        ///オンラインサイト
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KatakanaSpellcheck {
            get {
                return ResourceManager.GetString("KatakanaSpellcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A
        ///AA
        ///AAA
        ///Aachen
        ///Aachen&apos;s
        ///aah
        ///Aaliyah
        ///Aaliyah&apos;s
        ///aardvark
        ///aardvarks
        ///aardvark&apos;s
        ///Aaren
        ///Aaren&apos;s
        ///Aarika
        ///Aarika&apos;s
        ///Aaron
        ///Aaron&apos;s
        ///AB
        ///ABA
        ///aback
        ///abacus
        ///abacuses
        ///abacus&apos;s
        ///abaft
        ///Abagael
        ///Abagael&apos;s
        ///Abagail
        ///Abagail&apos;s
        ///abalone
        ///abalones
        ///abalone&apos;s
        ///abandon
        ///abandoned
        ///abandoning
        ///abandonment
        ///abandonment&apos;s
        ///abandons
        ///abase
        ///abased
        ///abasement
        ///abases
        ///abash
        ///abashed
        ///abashedly
        ///abashes
        ///abashing
        ///abashment
        ///abashment&apos;s
        ///abasing
        ///abate
        ///abated
        ///abatement
        ///abatement&apos;s
        ///abates
        ///abating
        ///abattoir
        ///abat [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Spellchecker_en {
            get {
                return ResourceManager.GetString("Spellchecker_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   node	ノード
        ///log	ログ
        ///software	ソフトウェア
        ///index	インデクス
        ///database	データベース
        ///data	データ
        ///instance	インスタンス
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpellingVariation_ja {
            get {
                return ResourceManager.GetString("SpellingVariation_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   big
        ///huge
        ///very
        ///lots
        ///about
        ///effort
        ///impact
        ///though
        ///thing
        ///things
        ///some
        ///a lot
        ///are after
        ///is after
        ///as a matter of fact
        ///as to whether
        ///as being
        ///at the end of the day
        ///completely
        ///at all times
        ///a large proportion of
        ///absolutely essential
        ///absolutely necessary
        ///advance forward
        ///almost unique
        ///alternative choice
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WeakExpressions_en {
            get {
                return ResourceManager.GetString("WeakExpressions_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7.71 the
        ///4.36 of
        ///3.31 and
        ///2.88 to
        ///2.11 in
        ///1.94 a
        ///1.38 that
        ///1.00 is
        ///0.99 it
        ///0.94 was
        ///0.85 for
        ///0.83 he
        ///0.82 as
        ///0.78 i
        ///0.74 by
        ///0.72 be
        ///0.70 his
        ///0.68 with
        ///0.64 not
        ///0.57 on
        ///0.56 which
        ///0.55 this
        ///0.54 or
        ///0.50 at
        ///0.49 but
        ///0.49 from
        ///0.45 had
        ///0.42 have
        ///0.40 you
        ///0.40 they
        ///0.39 are
        ///0.37 all
        ///0.33 we
        ///0.33 an
        ///0.32 were
        ///0.31 their
        ///0.30 him
        ///0.29 her
        ///0.28 one
        ///0.28 no
        ///0.27 so
        ///0.26 there
        ///0.25 if
        ///0.25 been
        ///0.25 who
        ///0.24 my
        ///0.24 them
        ///0.23 said
        ///0.22 she
        ///0.22 will
        ///0.22 when
        ///0.22 w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordFrequency_en {
            get {
                return ResourceManager.GetString("WordFrequency_en", resourceCulture);
            }
        }
    }
}
