//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPen.Net.Core {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedPen.Net.Core.ValidationMessage", typeof(ValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The number of commas in a sentence ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommaCount {
            get {
                return ResourceManager.GetString("CommaCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The abbreviation &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Contraction {
            get {
                return ResourceManager.GetString("Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple occurrences of the adversative conjunction particle &quot;{0}&quot; were found in a sentence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubledConjunctiveParticleGa {
            get {
                return ResourceManager.GetString("DoubledConjunctiveParticleGa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The particle &quot;{0}&quot; is used more than twice in a sentence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubledJoshi {
            get {
                return ResourceManager.GetString("DoubledJoshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The word &quot;{0}&quot; is used more than twice in a sentence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubledWord {
            get {
                return ResourceManager.GetString("DoubledWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A double negative expression &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubleNegative {
            get {
                return ResourceManager.GetString("DoubleNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A similar clause (starting from line {1}) was found for the section (starting from line {0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DuplicatedSection {
            get {
                return ResourceManager.GetString("DuplicatedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An empty section &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmptySection {
            get {
                return ResourceManager.GetString("EmptySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid sentence-ending expression &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndOfSentence {
            get {
                return ResourceManager.GetString("EndOfSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}% of sentences start with &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FrequentSentenceStart_SentenceStartTooFrequent {
            get {
                return ResourceManager.GetString("FrequentSentenceStart_SentenceStartTooFrequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The placement of section &quot;{0}&quot; (level {1}) is incorrect. Please relocate it to level {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GappedSection {
            get {
                return ResourceManager.GetString("GappedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The half-width katakana character &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HankakuKana {
            get {
                return ResourceManager.GetString("HankakuKana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The length of the heading ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HeaderLength {
            get {
                return ResourceManager.GetString("HeaderLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please use the hyphenated expression &quot;{1}&quot; for &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hyphenation_HyphenatedInDictionary {
            get {
                return ResourceManager.GetString("Hyphenation_HyphenatedInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid expression &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid brackets &quot;{0}&quot; were found. Please correct the types and numbers of opening and closing brackets to match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidParenthesis_MismatchedParentheses {
            get {
                return ResourceManager.GetString("InvalidParenthesis_MismatchedParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nesting level of parentheses ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidParenthesis_NestingLevelTooDeep {
            get {
                return ResourceManager.GetString("InvalidParenthesis_NestingLevelTooDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of parentheses in a sentence ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidParenthesis_SubsentenceTooFrequent {
            get {
                return ResourceManager.GetString("InvalidParenthesis_SubsentenceTooFrequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The length of the sentence inside the parentheses ({0} characters) exceeded the specified value ({1} characters). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidParenthesis_SubsentenceTooLong {
            get {
                return ResourceManager.GetString("InvalidParenthesis_SubsentenceTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid symbol &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidSymbol {
            get {
                return ResourceManager.GetString("InvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid word &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidWord {
            get {
                return ResourceManager.GetString("InvalidWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An ambiguous noun connection pattern &quot;{0}&quot; with consecutive &quot;の&quot; particles was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseAmbiguousNounConjunction {
            get {
                return ResourceManager.GetString("JapaneseAmbiguousNounConjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid chapter/section anchor &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseAnchorExpression {
            get {
                return ResourceManager.GetString("JapaneseAnchorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &quot;ra-nuki&quot; word &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseBrokenExpression {
            get {
                return ResourceManager.GetString("JapaneseBrokenExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A non-Joyo kanji character &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseJoyoKanji {
            get {
                return ResourceManager.GetString("JapaneseJoyoKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid counting expression &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseNumberExpression {
            get {
                return ResourceManager.GetString("JapaneseNumberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The use of an incorrect writing style &quot;{0}&quot; was found. Please unify the writing style to plain or polite form. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseStyle {
            get {
                return ResourceManager.GetString("JapaneseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; is considered a fluctuation expression of &quot;{1}&quot; (position: {2}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseWordVariation_Normal {
            get {
                return ResourceManager.GetString("JapaneseWordVariation_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; and &quot;{1}&quot; (position: {2}) are used the same number of times. One of them is considered a fluctuation expression. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseWordVariation_SameCount {
            get {
                return ResourceManager.GetString("JapaneseWordVariation_SameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid katakana word &quot;{0}&quot; containing a hyphen was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KatakanaEndHyphen {
            get {
                return ResourceManager.GetString("KatakanaEndHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The katakana word &quot;{0}&quot; is considered a fluctuation expression of &quot;{1}&quot; (position: {2}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KatakanaSpellCheck {
            get {
                return ResourceManager.GetString("KatakanaSpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The list level ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListLevel {
            get {
                return ResourceManager.GetString("ListLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of characters in the phrase &quot;{0}&quot; ({1} characters) exceeded the specified value ({2} characters). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LongKanjiChain {
            get {
                return ResourceManager.GetString("LongKanjiChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The decimal point symbol in the numeric expression &quot;{0}&quot; is used too many times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberFormat_TooManyDecimals {
            get {
                return ResourceManager.GetString("NumberFormat_TooManyDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The delimiter in the numeric expression &quot;{0}&quot; is invalid. A delimiter is required every three digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberFormat_UndelimitedSequenceTooLong {
            get {
                return ResourceManager.GetString("NumberFormat_UndelimitedSequenceTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The position of the delimiter in the numeric expression &quot;{0}&quot; is incorrect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberFormat_UndelimitedSequenceTooShort {
            get {
                return ResourceManager.GetString("NumberFormat_UndelimitedSequenceTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid okurigana &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Okurigana {
            get {
                return ResourceManager.GetString("Okurigana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of paragraphs in the section ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParagraphCount {
            get {
                return ResourceManager.GetString("ParagraphCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid paragraph start &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParagraphStartWith {
            get {
                return ResourceManager.GetString("ParagraphStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left quotes are used consecutively. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quotation_DoubleLeft {
            get {
                return ResourceManager.GetString("Quotation_DoubleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right quotes are used consecutively. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quotation_DoubleRight {
            get {
                return ResourceManager.GetString("Quotation_DoubleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The left quote is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quotation_LeftExist {
            get {
                return ResourceManager.GetString("Quotation_LeftExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no space next to the left quote. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quotation_LeftSpace {
            get {
                return ResourceManager.GetString("Quotation_LeftSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The right quote is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quotation_RightExist {
            get {
                return ResourceManager.GetString("Quotation_RightExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no space next to the right quote. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quotation_RightSpace {
            get {
                return ResourceManager.GetString("Quotation_RightSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; is a redundant expression. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedundantExpression {
            get {
                return ResourceManager.GetString("RedundantExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The level of clause &quot;{0}&quot; exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SectionLevel {
            get {
                return ResourceManager.GetString("SectionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of words in the section ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SectionWordCount {
            get {
                return ResourceManager.GetString("SectionWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The sentence length ({0} characters) exceeded the specified value ({1} characters). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SentenceLength {
            get {
                return ResourceManager.GetString("SentenceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of words in the sentence ({0}) exceeded the specified value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SentenceWordCount {
            get {
                return ResourceManager.GetString("SentenceWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no space at the beginning of the sentence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpaceBeginningOfSentence {
            get {
                return ResourceManager.GetString("SpaceBeginningOfSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A space is required after the half-width alphabet expression &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpaceWithAlphabeticalExpression_After {
            get {
                return ResourceManager.GetString("SpaceWithAlphabeticalExpression_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A space is required before the half-width alphabet expression &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpaceWithAlphabeticalExpression_Before {
            get {
                return ResourceManager.GetString("SpaceWithAlphabeticalExpression_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid spaces were found around the half-width alphabet expression &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpaceWithAlphabeticalExpression_Forbidden {
            get {
                return ResourceManager.GetString("SpaceWithAlphabeticalExpression_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A possibly misspelled word &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Spelling {
            get {
                return ResourceManager.GetString("Spelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A sentence starting with a lowercase letter &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartWithCapitalLetter {
            get {
                return ResourceManager.GetString("StartWithCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Similar sentences &quot;{0}&quot; and &quot;{1}&quot; are used consecutively. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuccessiveSentence {
            get {
                return ResourceManager.GetString("SuccessiveSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The word &quot;{0}&quot; is used consecutively. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuccessiveWord {
            get {
                return ResourceManager.GetString("SuccessiveWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid expression &quot;{0}&quot; was found. Consider using the alternative expression &quot;{1}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuggestExpression {
            get {
                return ResourceManager.GetString("SuggestExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The expression &quot;{0}&quot; matched the grammar rule &quot;{1}&quot;. Consider using the alternative expression &quot;{2}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuggestGrammarRule {
            get {
                return ResourceManager.GetString("SuggestGrammarRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A space is required after the symbol &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SymbolWithSpace_After {
            get {
                return ResourceManager.GetString("SymbolWithSpace_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A space is required before the symbol &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SymbolWithSpace_Before {
            get {
                return ResourceManager.GetString("SymbolWithSpace_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spaces are required before and after the symbol &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SymbolWithSpace_BeforeAfter {
            get {
                return ResourceManager.GetString("SymbolWithSpace_BeforeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &quot;taigen-dome&quot; (noun ending) &quot;{0}&quot; was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Taigendome {
            get {
                return ResourceManager.GetString("Taigendome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The formal expression for the abbreviation &quot;{0}&quot; was not found in the document. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnexpandedAcronym_UnexpandedAcronym {
            get {
                return ResourceManager.GetString("UnexpandedAcronym_UnexpandedAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The section content is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VoidSection {
            get {
                return ResourceManager.GetString("VoidSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; is a weak expression. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WeakExpression_WeakExpression {
            get {
                return ResourceManager.GetString("WeakExpression_WeakExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The word &quot;{0}&quot; is used {1}% of all words. The desired usage rate is around {2}%. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordFrequency_WordUsedTooFrequently {
            get {
                return ResourceManager.GetString("WordFrequency_WordUsedTooFrequently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of words in a sentence ({0}) exceeds the maximum value ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordNumber {
            get {
                return ResourceManager.GetString("WordNumber", resourceCulture);
            }
        }
    }
}
